import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <main className={styles.main}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className={styles.section} id={styles.Home}>
                <div className={styles.content}>
                    <div>
                        <div>
                            <Image
                                src={"/assets/logo.jpeg"}
                                width="240"
                                height="100"
                                alt="logo"
                            />
                            <p>
                                Local and Global FREE First Class Music
                                Consulting for Artists and music Enterpreneurs.
                            </p>
                            <a>ABOUT US</a>
                            <a>Disclaimer</a>
                            <span>POWERED BY GINGIO</span>
                        </div>

                        <div>
                            <div className={styles.chat}>
                                <p>chat</p>
                            </div>
                        </div>
                    </div>

                    <div className={styles.copyrights}>
                        <p>© 2022 GINGIO, Privacy Policy</p>
                    </div>
                </div>
            </section>

            <section className={styles.section}>
                <div className={styles.brandMission}>
                    <p>
                        Unify dreams and reality, connect yourself globally to
                    </p>
                    <p> BE MORE!</p>
                </div>
            </section>

            <section className={styles.section}>
                <div className={styles.about}>
                    <h3>ABOUT US</h3>
                    <p>
                        CEO and Creative Designer Jannik Olander was born in the
                        small country of Denmark. Though raised on the Danish
                        countryside, he was fascinated with style, energy, and
                        the arts from a young age. Through endeavors in the
                        fashion industry he was able to refine a distinct style
                        of beauty, quality, and spirituality. But it was not
                        until he traveled to the Far East that Jannik truly
                        gained the vision which inspired him to create the first
                        piece of Nialaya Jewelry. Jannik visited a local bazaar
                        on his first trip to India. While walking through the
                        crowded market he was stopped by a local Shaman who
                        asked to read his palm. The Shaman sat peacefully on a
                        blanket made of yellow silk. The once smooth fabric was
                        weathered and red dust covered parts of a once beautiful
                        golden French lily. The Shaman’s honest eyes were a calm
                        and piercing emerald green. Having felt a sincere and
                        calm energy from the man, he decided to give him a few
                        minutes of his time. He took a seat next to him. “First,
                        tell me your name”, said the Shaman. They sat in silence
                        as the Shaman looked deeply into Jannik’s eyes. He then
                        began to examine his palm.
                    </p>
                </div>
            </section>

            <section className={styles.section}>
                <p>
                    Please donate in order to keep our free service active for
                    the ones in need
                </p>
                <p>pic</p>
            </section>
        </main>
    );
}
