import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import whatsAppLogo from "../public/assets/WhatsApp.webp";
import gingioLogo from "../public/assets/gingio.png";
import payPalLogo from "../public/assets/Paypal.png";
import fmcLogoWhite from "../public/assets/logo-white.png";

export default function Home({ scrollTop, width, height, isSmallDevice }) {
    const [animationReady, setAnimationReady] = useState(false);
    const [overSection, setOverSection] = useState(false);
    const [chatButton, setChatButton] = useState(false);

    const [heading1Style, setHeading1Style] = useState(
        "heading-from-right-before"
    );
    const [heading2Style, setHeading2Style] = useState(
        "heading-fade-in-before"
    );

    useEffect(() => {
        const timer = setTimeout(() => {
            setAnimationReady(true);
        }, 800);
        return () => clearTimeout(timer);
    }, []);

    useEffect(() => {
        // INTERSECTION OBSERVER STUFF
        const io = new IntersectionObserver(
            (entries) => {
                entries.forEach((entry, i) => {
                    if (entry.isIntersecting) {
                        if (i === 0) {
                            setHeading1Style("heading-from-right-after");
                        }
                        if (i === 1) {
                            setHeading2Style("heading-fade-in-after");
                        }
                    } else {
                        return;
                    }
                });
            },
            {
                threshold: [0],
            }
        );
        // ELEMENTS TO OBSERVE
        const heading1 = document.querySelector("#heading1");
        const heading2 = document.querySelector("#heading2");
        // START OBSERVING ELEMENTS
        io.observe(heading1);
        io.observe(heading2);
    }, [scrollTop]);

    const renderAnimationA = animationReady
        ? {
              transform: "translateX(0)",
              opacity: "1",
          }
        : {
              transform: "translateX(-50%)",
              opacity: "0",
          };
    const renderAnimationB = animationReady
        ? {
              transform: "translateY(0)",
              opacity: "1",
          }
        : {
              transform: "translateY(-50px)",
              opacity: "0",
          };

    return (
        <>
            <main
                className={styles.main}
                style={
                    overSection
                        ? { transform: "translateX(-30%)" }
                        : { transform: "translateX(0)" }
                }
            >
                <Head>
                    <title>FMC • FREE First Class Music Consultant</title>
                    {/* <meta
                        name="description"
                        content="Generated by create next app"
                    /> */}
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <section className={styles.section} id={styles.Home}>
                    {width < 720 && (
                        <Image
                            src={"/assets/logo-white-subtitle.png"}
                            width="140"
                            height="65"
                            alt="logo"
                            className={styles.mobLogo}
                            style={renderAnimationA}
                        />
                    )}
                    <div className={styles.content}>
                        <div>
                            <div>
                                {width >= 720 && (
                                    <Image
                                        src={"/assets/logo-white-subtitle.png"}
                                        width="180"
                                        height="80"
                                        alt="logo"
                                        className={styles.logo}
                                        style={renderAnimationA}
                                    />
                                )}

                                <p
                                    className={styles.description}
                                    style={renderAnimationB}
                                >
                                    FREE first class music consulting service
                                    for Artists, Bands, Musicians and
                                    Entrepreneurs
                                </p>
                                <div className={styles.list}>
                                    <p
                                        onClick={() => setOverSection("about")}
                                        className={styles.navLink}
                                        style={renderAnimationB}
                                    >
                                        About us
                                    </p>
                                    <p
                                        onClick={() =>
                                            setOverSection("disclaimer")
                                        }
                                        className={styles.navLink}
                                        style={renderAnimationB}
                                    >
                                        Disclaimer
                                    </p>
                                    <span
                                        className={styles.poweredBy}
                                        style={renderAnimationA}
                                    >
                                        POWERED BY
                                        <a
                                            href="https://www.gingio.com"
                                            target="_blank"
                                            rel="noopener noreferrer"
                                        >
                                            <Image
                                                src={gingioLogo}
                                                width="auto"
                                                height={
                                                    width < 720 ? "15" : "20"
                                                }
                                                alt="Gingio Logo"
                                            />
                                        </a>
                                    </span>
                                </div>
                            </div>

                            <div>
                                {/* <div>
                                    <a
                                        href="https://wa.me/13102806893"
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className={styles.chat}
                                        onMouseEnter={() =>
                                            width > 460
                                                ? setChatButton(true)
                                                : setChatButton(false)
                                        }
                                        onMouseLeave={() =>
                                            setChatButton(false)
                                        }
                                        style={renderAnimationA}
                                    >
                                        <div
                                            className={styles.popout}
                                            style={
                                                chatButton
                                                    ? { width: "135px" }
                                                    : { width: "0" }
                                            }
                                        >
                                            <p
                                                style={
                                                    chatButton
                                                        ? {
                                                              opacity: "1",
                                                              transform:
                                                                  "translateX(0)",
                                                          }
                                                        : {
                                                              opacity: "0",
                                                              transform:
                                                                  "translateX(100%)",
                                                          }
                                                }
                                            >
                                                Chat with us!
                                            </p>
                                        </div>

                                        <Image
                                            src={whatsAppLogo}
                                            width="40"
                                            height="40"
                                            alt="WhatsApp Logo"
                                        />
                                    </a>
                                </div> */}

                                <script
                                    src="https://apps.elfsight.com/p/platform.js"
                                    defer
                                ></script>
                                <div className="elfsight-app-275bd947-d416-419c-9cce-a228d094f8f0"></div>
                            </div>
                        </div>

                        <div className={styles.copyrights}>
                            <p>
                                © {new Date().getFullYear()} GINGIO, Privacy
                                Policy
                            </p>
                        </div>
                    </div>
                </section>

                <section className={styles.section}>
                    <div className={styles.brandMission}>
                        <p id="heading1" className={heading1Style}>
                            Unify dreams and reality, connect yourself locally
                            and globally to
                        </p>
                        {/* <p id="heading1" className={heading1Style}>
                            Unify dreams and reality, connect yourself globally
                            to
                        </p> */}
                        <p id="heading2" className={heading2Style}>
                            BE MORE!
                        </p>
                    </div>
                </section>

                <section className={styles.smallSection}>
                    <div className={styles.donations}>
                        <div>
                            <p>
                                Please donate in order to keep our free service
                                active for the ones in need
                            </p>

                            <a
                                target="_blank"
                                rel="noopener noreferrer"
                                href="https://www.paypal.com/donate/?hosted_button_id=GFBJBUMRCRPYN"
                            >
                                {/* PAYPAL */}
                                <Image
                                    src={payPalLogo}
                                    layout="fill"
                                    objectFit="contain"
                                    alt="PayPal Logo"
                                />
                            </a>
                        </div>
                    </div>
                </section>
            </main>

            <section
                className={styles.section}
                id={styles.OverSection}
                style={
                    overSection
                        ? { transform: "translateX(0)", opacity: "1" }
                        : { transform: "translateX(100%)", opacity: "1" }
                }
            >
                <div>
                    <div>
                        <Image
                            src={fmcLogoWhite}
                            width="130"
                            height="auto"
                            // layout="fill"
                            // objectFit="contain"
                            alt="logo"
                            onClick={() => setOverSection(false)}
                        />
                    </div>
                    <span onClick={() => setOverSection(false)}>Close</span>
                </div>

                <div className={styles.about}>
                    {overSection === "about" && (
                        <>
                            {/* <h3>ABOUT US</h3> */}

                            <p>
                                FreeMusicConsultant.com is a FREE First Class
                                Music Consulting service offered online to
                                Artists, Bands, Engineers, Producers, Composers
                                and Entrepreneurs. Powered by the international
                                music consulting firm GINGIO who for the past 20
                                years has been delivering superior consulting
                                and coordination services to the global
                                entertainment industry professionals looking for
                                career direction as well as image, production,
                                promotion, marketing, business management or
                                expansion in general. GINGIO also features the
                                largest database of international music industry
                                contacts available in the market today. That is
                                why we are happy to share &quot;a contact or
                                two&quot; in the territory of interest from our
                                4.2 million music industry professionals
                                worldwide. The FMC Team assist people in need of
                                a quick cost-free advice, tips and contacts in
                                the music business locally as well as globally.
                                Let&apos;s chat via WhatsApp - We Love to help
                                music people in their career. Sometimes success
                                is just one tip/contact away!
                            </p>
                        </>
                    )}

                    {overSection === "disclaimer" && (
                        <>
                            {/* <h3>DISCLAIMER</h3> */}
                            <p>
                                Disclaimer of Liability The material and
                                information contained on this website is for
                                general information purposes only. You should
                                not rely upon the material or information on the
                                website as a basis for making any business,
                                legal or any other decisions. Whilst we endeavor
                                to keep the information up to date and correct,
                                GINGIO makes no representations or warranties of
                                any kind, express or implied about the
                                completeness, accuracy, reliability, suitability
                                or availability with respect to the website or
                                the information, products, services or related
                                graphics contained on the website for any
                                purpose. Any reliance you place on such material
                                is therefore strictly at your own risk.
                            </p>
                        </>
                    )}
                </div>
            </section>
        </>
    );
}
